### ISSUE TITLE
two questions abount the denoise_process

### ISSUE THREAD

**Issue by cl199443** [ykk648/AnimateDiff#7]
Some questions about the code    
- init_latents = self.vae.encode(image).latent_dist.sample(generator) .  After doing the encoder step, i see that no the normalize step 【 init_latents = init_latents * 0.18215  , but you do this  in the decoder step [latents = 1 / 0.18215 * latents]
- about adding noise into the init_latents to get x_t from x_0, i see that "timestep" is none in your code when strength<1, which means [scheduler.add_noise()] does not work, so i cant't understand that why  doing like this.

**Comment by ykk648** [comment]
1. init_latents func came from [talesofai](https://github.com/talesofai/AnimateDiff/blob/04b2715b39d4a02334b08cb6ee3dfe79f0a6cd7c/animatediff/pipelines/pipeline_animation.py#L288), the scale step was skiped, after that, the author did scale by himself ref [codes](https://github.com/talesofai/AnimateDiff/blob/04b2715b39d4a02334b08cb6ee3dfe79f0a6cd7c/animatediff/pipelines/pipeline_animation.py#L333). I thought this is only a scale step but not encoder step.
2. timestep codes was adapted from diffusers img2img by me, I deprecated it because it was not good enough so timestep is None. The `add noise` was made by hand. `scheduler.add_noise()` is also a scale procedure if you check the source codes.

correct me if I'm wrong 😄

**Comment by cl199443** [comment]
thanks for your feedback. For the question 2, you means that adding noise to the init_latent by hand using "latents[:, :, i, :, :] = init_latents * init_alpha + latents[:, :, i, :, :] * (1 - init_alpha)" , which somewhat equivalent to scheduler.add_noise().

**Comment by ykk648** [comment]
yep
